config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  resources :messages

  get 'admin/index'
  get 'admin/messages'

  get 'manager/index'
  get 'manager/messages'
  get 'manager/products'

  devise_for :admins
  get 'welcome/index'

  get '/carrinho' => 'welcome#cart', as: 'cart'

  resources :products

  namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    resources :messages, only: [:index, :create, :destroy, :update]
  end
end

   root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base

	validates_inclusion_of :tipo, :in => [true, false]
    validates :title, :body, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

before_action :authenticate_admin!

  def index
  	@bikes = Product.all
  end



end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < ApplicationController
   skip_before_filter :verify_authenticity_token,
                      :if => Proc.new { |c| c.request.format == 'application/json' }

  # Just skip the authentication for now
  # before_filter :authenticate_user!

  respond_to :json

  def index
     respond_with Message.all
#     render :text => '{
#   "success":true,
#   "info":"ok",
#   "data":{
#           "messages":[
#                     {"title":"Complete the app"},
#                     {"title":"Complete the tutorial"}
#                   ]
#          }
# }'
  end

  def create
    respond_with :api, :v1, Message.create(message_params)
  end

  def destroy
    respond_with Message.destroy(params[:id])
  end

  def update
   message = Message.find(params["id"])
   message.update_attributes(message_params)
   respond_with message, json: message
  end

  private

    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.permit(:title, :body, :tipo)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # para os post
  #skip_before_filter :verify_authenticity_token  


  #para o CORs
 after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected
    # In Rails 4.2 and above
  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end

  # In Rails 4.1 and below
  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController

before_action :authenticate_manager!

  def index
  	@bikes = Product.all
  end

  def products
  	@products = Product.all
  	
  end


   def messages
      @messages = Message.all.where( :tipo => false)
  end 
  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  skip_before_filter :verify_authenticity_token,
                     :if => Proc.new { |c| c.request.format == 'application/json' }

  before_action :authenticate_admin!, :except => [:create,:show]

  layout "frontend", :only => [:new, :create]

  respond_to :html, :json

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    @message.status = true
    @message.save
    respond_with(@message)
  end

  def new
    @message = Message.new
    respond_with(@message)
  end

  def edit
  end

  def create
      @message = Message.new(message_params)
     if @message.save!
      redirect_to root_path , notice: "Success"
    else
      flash.now[:notice] = "Error"
      render "new"
    end
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private

    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:title, :body, :status, :tipo)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

    layout "frontend", :only => [:index, :show]

    before_action :authenticate_manager! , :except => [:index,:show] 

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to manager_products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to manager_products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :model, :seller, :price, :picture, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
     layout "frontend"
  def index
  	@products = Product.all.limit(6)
  	@message = Message.new
  end

  def cart
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/messages.html.erb
<h1>Listagem de todas as mensagens</h1>

<table>
  <thead>
    <tr>
      <th>Ttitulo</th>
      <th>Assunto</th>
      <th>Vista ?</th>
      <th> tipo </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= message.body %></td>
        <td><%= message.status %></td>
        <td><%= message.tipo %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Editar', edit_message_path(message) %></td>
        <td><%= link_to 'Apagar', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/_header.html.erb
<div class="banner-bg banner-sec">	
	  <div class="container">
			 <div class="header">
			       <div class="logo">
						 <%= link_to  root_path do %>
						 <img src="../images/logo.png" alt=""/>
						 <% end %>
				   </div>
				  <div class="top-nav">
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
						  <li class="dropdown1"><a href="bicycles.html">BICICLETAS</a>
							  <ul class="dropdown2">
									<li><%= link_to " Loja Online", products_path  %></li>
							  </ul>
						  </li>
						
						 </li>      
						
						 </li>               
						 <li class="dropdown1"><a href="#">LOGIN</a>
						  <ul class="dropdown2">
									<li> <%= link_to('Adimintrador', admin_index_path)  %> </li>
									<li> <%= link_to('Gestor', manager_index_path)  %> </li>
							  </ul>
						 </li>
						  <%= link_to  cart_path, :class => "shop" do %><img src="../images/cart.png" alt=""/>
						<% end %>
						 
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div> 				 
</div>

app/views/layouts/_header_index.html.erb
<div class="banner-bg banner-bg1">	
	  <div class="container">
			 <div class="header">
			       <div class="logo">
			       		 <%= link_to  root_path do %>
						 <img src="images/logo.png" alt=""/>
						 <% end %>
				   </div>							 
				  <div class="top-nav">										 
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
						  <li class="dropdown1"><a href="bicycles.html">BICICLETAS</a>
							  <ul class="dropdown2">
									<li><%= link_to " Loja Online", products_path  %></li>
																				
							  </ul>
						  </li>
						  <li class="dropdown1"><a href="parts.html">PARTS</a>
							 <ul class="dropdown2">
									<li>CHAINS</a></li>
									<li>TUBES</a></li>
									<li>TIRES</a></li>
									<li>DISC BREAKS</a></li>
							  </ul>
						 </li>      
					            
						 <li class="dropdown1"><a href="#">LOGIN</a>
						  <ul class="dropdown2">
									<li> <%= link_to('Adimintrador', admin_index_path)  %> </li>
									<li> <%= link_to('Gestor', manager_index_path)  %> </li>
							  </ul>
						 </li>
						 <%= link_to  cart_path, :class => "shop" do %><img src="../images/cart.png" alt=""/>
						<% end %>
						 
						
						 
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div>	 
	 <div class="caption">
		 <div class="slider">
					   <div class="callbacks_container">
						   <ul class="rslides" id="slider">
							    <li><h1>HANDMADE BICYCLE</h1></li>
								<li><h1>SPEED BICYCLE</h1></li>	
								<li><h1>MOUINTAIN BICYCLE</h1></li>	
						  </ul>
						  <p>You <span>create</span> the <span>journey,</span> we supply the <span>parts</span></p>
						  
						  <%= link_to " Loja Online", products_path , :class => "morebtn" %>
					  </div>
				  </div>
	 </div>
	 <div class="dwn">
		<a class="scroll" href="#cate"><img src="images/scroll.png" alt=""/></a>
	 </div>				 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<% if current_admin %>
  <title>Administrador</title>
<% end %>
  <title>Gestor de produto</title>

  <link href="../font-awesome/css/font-awesome.css" rel="stylesheet" />
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--Header-part-->
<div id="header">
  <h1><a href="dashboard.html">Bikes Admin</a></h1>
</div>
<!--close-Header-part--> 

<% if current_admin  %>
<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Bemvindo <%= current_admin.email %></span><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
      
         <%= link_to edit_admin_registration_path, :method => :delete do %>
        <i class="icon-key"></i>Ver perfil
        <% end %></li>
        <li class="divider"></li>
        <li><a href="#"><i class="icon-check"></i> Minhas Mensagens</a></li>
        <li class="divider"></li>
       
        <%= link_to destroy_admin_session_path, :method => :delete do %>
        <i class="icon-key"></i>Log Out
        <% end %>  
        </li>
      </ul>
    </li>
    <li class="dropdown" id="menu-messages"><%= link_to  messages_path, :class=>"dropdown-toggle" do %><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important"><%= Message.all.size %></span> <b class="caret"></b> <% end %>
    </li>
    <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
    <li class="">
     <%= link_to destroy_admin_session_path, :method => :delete do %>
     <i class="icon icon-share-alt"></i> <span class="text">Logout</span>
     <% end %></li>
  </ul>
</div>
<!--close-top-Header-menu-->
<!--start-top-serch-->
<div id="search">
  <input type="text" placeholder="Search here..."/>
  <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
</div>
<!--close-top-serch-->
<!--sidebar-menu-->
<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
  <ul>
    <li class="active"><a href="index.html"><i class="icon icon-home"></i> <span>Dashboard</span></a> </li>
  
   
    
    <%= link_to  messages_path do %><i class="icon icon-inbox"></i> <span>Ver Mensagens</span> <span class="label label-important"> - </span><% end %></li>
   
  
    <br>
    
    <li class="content"> <span>Monthly Bandwidth Transfer</span>
      <div class="progress progress-mini progress-danger active progress-striped">
        <div style="width: 77%;" class="bar"></div>
      </div>
      <span class="percent">77%</span>
      <div class="stat">21419.94 / 14000 MB</div>
    </li>
    <li class="content"> <span>Disk Space Usage</span>
      <div class="progress progress-mini active progress-striped">
        <div style="width: 87%;" class="bar"></div>
      </div>
      <span class="percent">87%</span>
      <div class="stat">604.44 / 4000 MB</div>
    </li>
  </ul>
</div>
<!--sidebar-menu-->
<% end -%>

<% if current_manager  %>
<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Gestor <%= current_manager.email %></span><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
      
         <%= link_to edit_manager_registration_path, :method => :delete do %>
        <i class="icon-key"></i>Ver perfil
        <% end %></li>
        <li class="divider"></li>
        <li><a href="#"><i class="icon-check"></i> Minhas Mensagens</a></li>
        <li class="divider"></li>
       
        <%= link_to destroy_manager_session_path, :method => :delete do %>
        <i class="icon-key"></i>Log Out
        <% end %>  
        </li>
      </ul>
    </li>
     <li class="dropdown" id="menu-messages"><%= link_to  manager_messages_path, :class=>"dropdown-toggle" do %><i class="icon icon-envelope"></i> <span class="text">Mensagens</span>  <b class="caret"></b> <% end %>
    </li>
    <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
    <li class="">
     <%= link_to destroy_manager_session_path, :method => :delete do %>
     <i class="icon icon-share-alt"></i> <span class="text">Logout</span>
     <% end %></li>
  </ul>
</div>
<!--close-top-Header-menu-->
<!--start-top-serch-->
<div id="search">
  <input type="text" placeholder="Search here..."/>
  <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
</div>
<!--close-top-serch-->
<!--sidebar-menu-->
<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
  <ul>
    <li class="active"><a href="index.html"><i class="icon icon-home"></i> <span>Dashboard</span></a> </li>
  
    <li><%= link_to  manager_products_path do %><i class="icon icon-th"></i> <span>Ver Bicicletas</span><span class="label label-important">
      <%= Product.all.size %>
    </span> <% end %></li>
    <li>
  
   <%= link_to  manager_messages_path do %><i class="icon icon-inbox"></i> <span>Ver Mensagens</span> <% end %></li>
   
    
    </li>
  </ul>
</div>
<!--sidebar-menu-->
<% end -%>



<!--main-container-part-->
<div id="content">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</div>

<!--Footer-part-->

<div class="row-fluid">
  <div id="footer" class="span12"> 2013 &copy; Htrix Admin. Brought to you by <a href="http://hctec.pt">HCtec</a> </div>
</div>

<!--end-Footer-part-->


<script type="text/javascript">
  // This function is called from the pop-up menus to transfer to
  // a different page. Ignore if the value returned is a null string:
  function goPage (newURL) {

      // if url is empty, skip the menu dividers and reset the menu selection to default
      if (newURL != "") {
      
          // if url is "-", it is this page -- reset the menu:
          if (newURL == "-" ) {
              resetMenu();            
          } 
          // else, send page to designated URL            
          else {  
            document.location.href = newURL;
          }
      }
  }

// resets the menu selection upon entry to this page:
function resetMenu() {
   document.gomenu.selector.selectedIndex = 2;
}
</script>

</body>
</html>

app/views/manager/messages.html.erb
<h1>Listagem de mensagens para apoio aos Produtos</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Vista ?</th>
      <th>tipo </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
       
        <td><% if message.status %> VISTO <% else %> Não Visto <% end %></td>
        <td><%if message.tipo %> Para Produtos <% end %></td>
        <td><%= link_to 'mostar', message %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/manager/products.html.erb
<h1>Listagem de Bicicletas</h1>
<div class="table-responsive">
  <table class="table table-bordered">
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Modelo</th>
      <th>Vendedor</th>
      <th>Preço</th>
      <th>Fotografia</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to  product.name %></td>
        <td><%= product.model %></td>
        <td><%= product.seller %></td>
        <td><%= product.price %></td>
        <td><%= image_tag product.picture_url(:thumb) if product.picture? %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Mostrar', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Destruir', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Introduzir uma nova Bicicleta', new_product_path, :class => "btn btn-info"%>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= message.body %></td>
        <td><%= message.status %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @message.status %>
</p>
<p>
  <strong>tipo:</strong>
  <%= @message.tipo %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<% if current_admin %>
<%= link_to 'Back', messages_path %>
<% else %>
<%= link_to 'Back', manager_messages_path %>	
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/new.html.erb
<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a></div>
  </div>
<!--End-breadcrumbs-->

<!--Action boxes-->
  <div class="container-fluid">
    <div class="quick-actions_homepage">

<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', manager_products_path %>

</div></div>

app/views/products/show.html.erb
<%# link_to 'Edit', edit_product_path(@product) %> |
<%# link_to 'Back', products_path %>

<div class="product">
   <div class="container">
     <div class="ctnt-bar cntnt">
       <div class="content-bar">
         <div class="single-page">
           <div class="product-head">
            <a href="index.html">Home</a> <span>::</span> 
            </div>
           <!--Include the Etalage files-->
            <link rel="stylesheet" href="css/etalage.css">
            <script src="js/jquery.etalage.min.js"></script>
        <script>
      jQuery(document).ready(function($){

        $('#etalage').etalage({
          thumb_image_width: 400,
          thumb_image_height: 400,
          source_image_width: 800,
          source_image_height: 1000,
          show_hint: true,
          click_callback: function(image_anchor, instance_id){
            alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
          }
        });

      });
    </script>
            <!--//details-product-slider-->
           <div class="details-left-slider">
             <div class="grid images_3_of_2">
              <ul id="etalage">
              <li>
                
             <%= image_tag @product.picture_url(:thumb) if @product.picture? %>
                
                <%= image_tag(@product.picture_url, :class => "etalage_source_image", :class => "img-responsive") if @product.picture.present? %>

                  <!-- <img class="etalage_source_image" src="../images/m1.jpg" class="img-responsive" title="" /> -->
                
              </li>
             
            </ul>
            </div>
           </div>
           <div class="details-left-info">
              <h3> <%= @product.name %></h3>
                <h4>Modelo :  <%= @product.model %></h4>
              <h4></h4>
              <p><label>€ </label>  <%= @product.price %> <a href="#">Click for offer</a></p>
              <p class="size">SIZE ::</p>
              <a class="length" href="#">XS</a>
              <a class="length" href="#">M</a>
              <a class="length" href="#">S</a>
              <div class="btn_form">
                <a href="cart.html">buy now</a>
                <a href="cart.html">ADD TO CART</a>
              </div>
              <div class="bike-type">
              <p>TYPE  ::<a href="#">MOUNTAIN BIKE</a></p>
              <p>BRAND  ::<a href="#"> <%= @product.seller %></a></p>
              </div>
              <h5>Descrção  ::</h5>
              <p class="desc"> <%= @product.description %></p>
           </div>
           <div class="clearfix"></div>         
          </div>
        </div>
      </div>
      <div class="single-bottom2">
        <h6>Related Products</h6>
       <div class="product">
           <div class="product-desc">
              <div class="product-img product-img2">
               <img src="../images/s1.jpg" class="img-responsive " alt=""/>
             </div>
             <div class="prod1-desc">
                <h5><a class="product_link" href="bicycles.html">Road Bike</a></h5>
                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra. </p>                 
             </div>
             <div class="clearfix"></div>
           </div>
           <div class="product_price">
              <span class="price-access">$300.51</span>               
              <a class="button1" href="cart.html"><span>Add to cart</span></a>
           </div>
            <div class="clearfix"></div>
       </div>
       <div class="product">
           <div class="product-desc">
              <div class="product-img product-img2">
               <img src="../images/s2.jpg" class="img-responsive " alt=""/>
             </div>
             <div class="prod1-desc">
                <h5><a class="product_link" href="bicycles.html">Mountain Bike</a></h5>
                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra. </p>                 
             </div>
             <div class="clearfix"></div>
           </div>
           <div class="product_price">
              <span class="price-access">$1500.51</span>                
              <a class="button1" href="cart.html"><span>Add to cart</span></a>
           </div>
          <div class="clearfix"></div>
       </div>
       <div class="product">
           <div class="product-desc">
              <div class="product-img product-img2">
               <img src="../images/s3.jpg" class="img-responsive " alt=""/>
             </div>
             <div class="prod1-desc">
                <h5><a class="product_link" href="bicycles.html">Single Speed Bike</a></h5>
                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra. </p>                 
             </div>
             <div class="clearfix"></div>
           </div>
           <div class="product_price">
              <span class="price-access">$800.51</span>               
              <a class="button1" href="cart.html"><span>Add to cart</span></a>
           </div>
         <div class="clearfix"></div>
        </div>
     </div> 
   </div>
</div>